(ns hpke.rfc9180-test
  "Every mode of every appendix of RFC 9180, against the RFC.

  Seven appendices, four modes each. The suite for each is built **from the
  identifiers the vectors themselves declare** — `kem_id`, `kdf_id`,
  `aead_id`, looked up in this library's registries — so the test also checks
  that those registries map an identifier to the implementation the RFC means
  by it, which no hand-written suite constant could.

  None of what follows is another implementation's answer; the differential
  oracle in `oracle/` is a second opinion, not the first one.

  The vectors are generated by `scripts/extract_rfc9180.cljs` from a text
  pinned by sha256, because transcription is the step that has failed here
  before: an earlier suite claimed A.2 vectors and had A.1's `ikmR`.

  ## What each mode is asked

  `DeriveKeyPair` on every ikm the section publishes, then the KEM's own
  output (`enc` and `shared_secret`), then the key schedule (`key`,
  `base_nonce`, `exporter_secret`, and `key_schedule_context` — the value the
  four modes actually differ in), then six sealings at the published sequence
  numbers, then three exports, then the whole thing again from the recipient
  side.

  The sequence numbers are 0, 1, 2, 4, 255 and 256. The last two are the
  reason to assert them: 255 and 256 are where a byte-at-a-time nonce counter
  carries, and `compute-nonce` builds its bytes by division precisely so that
  it can."
  (:require [clojure.test :refer [deftest is testing]]
            [hpke.core :as hpke]
            [ecc.bignum :as bn]
            [hpke.dhkem :as dhkem]
            [hpke.kdf :as kdf]
            [hpke.rfc9180-vectors :as rfc]))

(defn- h [s] (hpke/unhex s))
(defn- x [bs] (hpke/hex bs))
(defn- n [s] #?(:clj (Long/parseLong s) :cljs (js/parseInt s 10)))

(defn- kp
  "The key pair a section publishes, derived rather than read.

  Both are asserted: deriving it exercises `DeriveKeyPair`, and comparing it
  to the published `sk`/`pk` is what makes the derivation checkable. A wrong
  `DeriveKeyPair` is the one failure in this file that would otherwise be
  silent — every later value would be self-consistently wrong."
  [v ikm-k sk-k pk-k]
  (let [d (dhkem/derive-key-pair (h (get v ikm-k)))]
    (is (= (get v sk-k) (x (:private d))) (str ikm-k " -> " sk-k))
    (is (= (get v pk-k) (x (:public d))) (str ikm-k " -> " pk-k))
    d))

(defn- check-context
  "The four key-schedule outputs the RFC publishes."
  [v ctx label]
  (testing label
    (is (= (:key-schedule-context v) (x (:key-schedule-context ctx))) "key_schedule_context")
    (is (= (:key v) (x (:key ctx))) "key")
    (is (= (:base-nonce v) (x (:base-nonce ctx))) "base_nonce")
    (is (= (:exporter-secret v) (x (:exporter-secret ctx))) "exporter_secret")))

(defn- check-encryptions
  [v ctx]
  (doseq [e (:encryptions v)]
    (testing (str "seq " (:sequence-number e))
      (let [at (assoc ctx :seq (n (:sequence-number e)))
            sealed (hpke/seal at (h (:aad e)) (h (:pt e)))]
        (is (= :ok (:status sealed)))
        (is (= (:ct e) (x (:bytes sealed))) "ct")
        (let [opened (hpke/open at (h (:aad e)) (h (:ct e)))]
          (is (= :ok (:status opened)))
          (is (= (:pt e) (x (:bytes opened))) "pt")
          (is (= (inc (n (:sequence-number e))) (:seq (:context opened)))
              "open advances the sequence number"))))))

(defn- check-exports
  [v ctx]
  (doseq [e (:exports v)]
    (testing (str "export ctx=" (pr-str (:exporter-context e)))
      (is (= (:exported-value e)
             (x (hpke/export ctx (h (:exporter-context e)) (n (:l e)))))))))

(defn- check-kem
  "`enc` and `shared_secret` — the KEM's own two outputs, before the key
  schedule touches them."
  [v kem]
  (is (= :ok (:status kem)))
  (is (= (:enc v) (x (:enc kem))) "enc")
  (is (= (:shared-secret v) (x (:shared-secret kem))) "shared_secret"))

;; ── the four modes ───────────────────────────────────────────────────────────

(defn- vecs [app k] (get-in rfc/by-appendix [app k]))
(def ^:private suite-of {:a1 hpke/aes-128-gcm :a2 hpke/chacha20-poly1305})

(defn- n [s] #?(:clj (Long/parseLong s) :cljs (js/parseInt s 10)))

(defn- suite-of
  "The suite an appendix declares, assembled from the registries.

  If `kems`, `kdfs` or `aeads` ever maps an identifier to the wrong thing,
  every vector in that appendix fails — which is a stronger statement than a
  hand-written constant, because a hand-written constant would agree with the
  same mistake."
  [v]
  (hpke/suite (get dhkem/kems (n (:kem-id v)))
              (get kdf/kdfs (n (:kdf-id v)))
              (get hpke/aeads (n (:aead-id v)))))

(defn- kp
  "The key pair a section publishes, derived rather than read.

  Both are asserted: deriving it exercises `DeriveKeyPair` — including the
  rejection sampling the NIST curves need — and comparing it to the published
  `sk`/`pk` is what makes the derivation checkable. A wrong `DeriveKeyPair` is
  the one failure here that would otherwise be silent, because every later
  value would be self-consistently wrong."
  [kem v ikm-k sk-k pk-k]
  (let [d (dhkem/derive-key-pair kem (h (get v ikm-k)))]
    (is (= :ok (:status d)) (str ikm-k))
    (is (= (get v sk-k) (x (:private d))) (str ikm-k " -> " sk-k))
    (is (= (get v pk-k) (x (:public d))) (str ikm-k " -> " pk-k))
    d))

(defn- check-context [v ctx label]
  (testing label
    (is (= (:key-schedule-context v) (x (:key-schedule-context ctx))) "key_schedule_context")
    (is (= (:exporter-secret v) (x (:exporter-secret ctx))) "exporter_secret")
    (if (seq (:key v))
      (do (is (= (:key v) (x (:key ctx))) "key")
          (is (= (:base-nonce v) (x (:base-nonce ctx))) "base_nonce"))
      (testing "export-only: the RFC publishes no key and none is derived"
        (is (nil? (:key ctx)))
        (is (nil? (:base-nonce ctx)))))))

(defn- check-encryptions [v ctx]
  (doseq [e (:encryptions v)]
    (testing (str "seq " (:sequence-number e))
      (let [at (assoc ctx :seq (n (:sequence-number e)))
            sealed (hpke/seal at (h (:aad e)) (h (:pt e)))]
        (is (= :ok (:status sealed)))
        (is (= (:ct e) (x (:bytes sealed))) "ct")
        (let [opened (hpke/open at (h (:aad e)) (h (:ct e)))]
          (is (= :ok (:status opened)))
          (is (= (:pt e) (x (:bytes opened))) "pt")
          (is (= (inc (n (:sequence-number e))) (:seq (:context opened)))
              "open advances the sequence number"))))))

(defn- check-exports [v ctx]
  (doseq [e (:exports v)]
    (testing (str "export ctx=" (pr-str (:exporter-context e)))
      (is (= (:exported-value e)
             (x (hpke/export ctx (h (:exporter-context e)) (n (:l e)))))))))

(def ^:private mode-of {:base 0 :psk 1 :auth 2 :auth-psk 3})

(deftest every-appendix-every-mode
  (doseq [app [:a1 :a2 :a3 :a4 :a5 :a6 :a7]
          [k mode-n] mode-of]
    (let [v (get-in rfc/by-appendix [app k])
          s (suite-of v)
          kem (:kem s)
          info (h (:info v))
          psk (when (seq (:psk v)) (h (:psk v)))
          psk-id (when (seq (:psk-id v)) (h (:psk-id v)))
          eph (kp kem v :ikme :skem :pkem)
          r (kp kem v :ikmr :skrm :pkrm)
          snd (when (:ikms v) (kp kem v :ikms :sksm :pksm))]
      (testing (str (name app) " " (name k))
        (is (= mode-n (n (:mode v))) "the section is the mode it says")
        (is (some? kem) "the KEM registry has this kem_id")
        (is (some? (:kdf s)) "and the KDF registry this kdf_id")
        (is (some? (:aead s)) "and the AEAD registry this aead_id")

        (testing "the KEM's own outputs, before the key schedule"
          (let [k' (if snd
                     (dhkem/auth-encap kem (:public r) eph snd)
                     (dhkem/encap kem (:public r) eph))]
            (is (= :ok (:status k')))
            (is (= (:enc v) (x (:enc k'))) "enc")
            (is (= (:shared-secret v) (x (:shared-secret k'))) "shared_secret")))

        (let [setup (case k
                      :base (hpke/setup-base-sender s (:public r) info eph)
                      :psk (hpke/setup-psk-sender s (:public r) info psk psk-id eph)
                      :auth (hpke/setup-auth-sender s (:public r) info eph snd)
                      :auth-psk (hpke/setup-auth-psk-sender s (:public r) info psk psk-id eph snd))]
          (is (= :ok (:status setup)))
          (is (= (:enc v) (x (:enc setup))) "enc")
          (check-context v (:context setup) "sender")
          (check-encryptions v (:context setup))
          (check-exports v (:context setup)))

        (let [rc (case k
                   :base (hpke/setup-base-recipient s (h (:enc v)) r info)
                   :psk (hpke/setup-psk-recipient s (h (:enc v)) r info psk psk-id)
                   :auth (hpke/setup-auth-recipient s (h (:enc v)) r info (:public snd))
                   :auth-psk (hpke/setup-auth-psk-recipient s (h (:enc v)) r info psk psk-id (:public snd)))]
          (is (= :ok (:status rc)))
          (check-context v (:context rc) "recipient")
          (check-encryptions v (:context rc))
          (check-exports v (:context rc)))))))

;; ── what the seven appendices pin between them ───────────────────────────────

(deftest the-appendices-cover-the-axes-this-library-parameterises
  (let [ids (fn [k] (set (map #(n (get-in rfc/by-appendix [% :base k]))
                              [:a1 :a2 :a3 :a4 :a5 :a6 :a7])))]
    (is (= #{0x0020 0x0010 0x0012} (ids :kem-id))
        "X25519, P-256 and P-521 — but not P-384 and not X448")
    (is (= #{0x0001 0x0003} (ids :kdf-id))
        "HKDF-SHA256 and HKDF-SHA512 — but not HKDF-SHA384")
    (is (= #{0x0001 0x0002 0x0003 0xFFFF} (ids :aead-id))
        "all four AEADs, including export-only")))

(deftest a4-is-the-one-that-proves-the-kem-keeps-its-own-kdf
  ;; DHKEM(P-256, HKDF-SHA256) paired with HKDF-SHA512. The KEM derives with
  ;; SHA-256 and the key schedule with SHA-512, in the same suite. A library
  ;; that read one KDF for both would be right about six appendices.
  (let [v (get-in rfc/by-appendix [:a4 :base])
        s (suite-of v)]
    (is (= 0x0010 (n (:kem-id v))))
    (is (= 0x0003 (n (:kdf-id v))))
    (is (= 0x0001 (:kdf-id (:kdf (:kem s)))) "the KEM's KDF is HKDF-SHA256")
    (is (= 0x0003 (:kdf-id (:kdf s))) "the suite's KDF is HKDF-SHA512")
    (is (not= (:kdf-id (:kdf (:kem s))) (:kdf-id (:kdf s)))
        "and they differ, which is the whole point of this appendix")
    (testing "the same KEM under A.3 derives the same key pair, because the
              KEM's KDF did not change with the suite's"
      (is (= (:pkrm (get-in rfc/by-appendix [:a3 :base]))
             (x (:public (dhkem/derive-key-pair
                          (:kem s)
                          (h (:ikmr (get-in rfc/by-appendix [:a3 :base]))))))))) ))

(deftest export-only-refuses-to-encrypt
  (let [v (get-in rfc/by-appendix [:a7 :base])
        s (suite-of v)
        r (dhkem/derive-key-pair! (:kem s) (h (:ikmr v)))
        eph (dhkem/derive-key-pair! (:kem s) (h (:ikme v)))
        setup (hpke/setup-base-sender s (:public r) (h (:info v)) eph)]
    (is (= 0xFFFF (:aead-id s)))
    (is (= 0 (:nk s)))
    (is (= :export-only-aead (:reason (hpke/seal (:context setup) [] [1 2 3]))))
    (is (= :export-only-aead (:reason (hpke/open (:context setup) [] (vec (repeat 32 0))))))
    (testing "but exporting is exactly what it is for"
      (is (= (:exported-value (first (:exports v)))
             (x (hpke/export (:context setup) [] 32)))))))

(deftest the-registries-list-only-what-runs
  (is (= #{0x0010 0x0011 0x0012 0x0020 0x0021} (set (keys dhkem/kems))))
  (is (= #{0x0001 0x0002 0x0003} (set (keys kdf/kdfs))))
  (is (= #{0x0001 0x0002 0x0003 0xFFFF} (set (keys hpke/aeads))))
  (testing "and the two the RFC's appendices do not reach still work"
    ;; P-384 and X448 have no RFC 9180 appendix. Their evidence is the
    ;; complete Wycheproof corpus in org-nist-ecc and org-ietf-x448; here
    ;; they get a round-trip, and it is labelled as one rather than sitting
    ;; among the known-answer tests as if it were the same claim.
    (doseq [kem [dhkem/p384-hkdf-sha384 dhkem/x448-hkdf-sha512]]
      (let [s (hpke/suite kem (:kdf kem) hpke/aes-256-gcm)
            r (dhkem/derive-key-pair! kem (vec (range (:nsk kem))))
            eph (dhkem/derive-key-pair! kem (vec (range 1 (inc (:nsk kem)))))
            snd (dhkem/derive-key-pair! kem (vec (range 2 (+ 2 (:nsk kem)))))
            pt (h "48656c6c6f") aad (h "0102")]
        (testing (str (name (:name kem)) " base")
          (let [sent (hpke/seal-base s (:public r) [] aad pt eph)]
            (is (= :ok (:status sent)))
            (is (= pt (:bytes (hpke/open-base s (:enc sent) r [] aad (:bytes sent)))))))
        (testing (str (name (:name kem)) " auth")
          (let [sent (hpke/seal-auth s (:public r) [] aad pt eph snd)]
            (is (= :ok (:status sent)))
            (is (= pt (:bytes (hpke/open-auth s (:enc sent) r [] aad (:bytes sent) (:public snd)))))
            (is (= :authentication-failed
                   (:reason (hpke/open-auth s (:enc sent) r [] aad (:bytes sent) (:public r))))
                "and a wrong sender key is rejected by the AEAD")))))))

;; ── the branch no ikm can reach ─────────────────────────────────────────────

(deftest rejection-sampling-rejects-at-the-boundary
  ;; RFC 9180 §7.1.3 draws candidates until one is in [1, order). The path
  ;; that *rejects* cannot be reached by supplying an ikm: for P-256 a masked
  ;; candidate falls outside the range with probability about 2^-32, and for
  ;; P-521 the bitmask leaves 521 bits against an order within 2^-260 of that.
  ;;
  ;; Measured: forcing the condition to accept everything left the whole RFC
  ;; suite green. A branch nothing reaches is a branch nothing checks, so the
  ;; condition is a named predicate and it is checked directly.
  (doseq [kem [dhkem/p256-hkdf-sha256 dhkem/p384-hkdf-sha384 dhkem/p521-hkdf-sha512]]
    (let [order (:n (:curve kem))]
      (testing (name (:name kem))
        (is (not (dhkem/candidate-acceptable? bn/zero order))
            "zero is rejected — it multiplies to infinity")
        (is (dhkem/candidate-acceptable? bn/one order)
            "one is the smallest accepted")
        (is (dhkem/candidate-acceptable? (bn/sub order bn/one) order)
            "order-1 is the largest accepted")
        (is (not (dhkem/candidate-acceptable? order order))
            "the order itself is rejected — it multiplies to infinity too")
        (is (not (dhkem/candidate-acceptable? (bn/add order bn/one) order))
            "and anything above it is a different scalar than the peer derives")))))

(deftest the-p521-bitmask-is-not-the-others
  ;; 0x01, not 0xFF. Its order is 521 bits inside 66 bytes, so all but one bit
  ;; of the leading byte must be cleared -- with 0xFF every candidate would be
  ;; far above the order and the loop would exhaust its counter.
  (is (= 0xFF (:bitmask dhkem/p256-hkdf-sha256)))
  (is (= 0xFF (:bitmask dhkem/p384-hkdf-sha384)))
  (is (= 0x01 (:bitmask dhkem/p521-hkdf-sha512)))
  (testing "the mask brings a candidate to the right size — and that is not
            the same as bringing it into range"
    (let [order (:n (:curve dhkem/p521-hkdf-sha512))
          all-ones (vec (repeat 66 0xFF))
          unmasked (bn/of-bytes all-ones)
          masked (bn/of-bytes (assoc all-ones 0 0x01))]
      (is (not (dhkem/candidate-acceptable? unmasked order))
          "528 bits is far above the order")
      (is (not (dhkem/candidate-acceptable? masked order))
          "and 521 bits of ones is STILL above it — 2^521-1 is the field prime,
           which exceeds the group order. This is the case that shows why
           masking alone is not enough and the rejection loop has to exist.")
      (is (dhkem/candidate-acceptable? (bn/of-bytes (assoc (vec (repeat 66 0x00)) 65 0x07))
                                       order)
          "a small masked candidate is in range, which is the ordinary case"))))

(deftest the-zero-salt-length-cannot-be-observed-and-that-is-why
  ;; RFC 5869 §2.2: an absent salt is Nh zero bytes. Substituting 32 for Nh
  ;; changes nothing measurable -- HMAC zero-pads a key shorter than its block
  ;; to the block, and 32, 48 and 64 are all shorter than 64 or 128. An
  ;; attempted break that made the zero salt always 32 bytes produced zero
  ;; failures, and that is a property of HMAC rather than a missing test.
  ;;
  ;; Asserted here so the equivalence is written down rather than rediscovered
  ;; the next time someone "fixes" it -- and so the boundary where it stops
  ;; holding is on record.
  (doseq [k [kdf/hkdf-sha256 kdf/hkdf-sha384 kdf/hkdf-sha512]]
    (testing (str "kdf " (:kdf-id k))
      (let [ikm [1 2 3]
            nh-zeros (kdf/extract k (vec (repeat (:nh k) 0)) ikm)]
        (is (= nh-zeros (kdf/extract k [] ikm))
            "an empty salt is Nh zeros")
        (is (= nh-zeros (kdf/extract k (vec (repeat 32 0)) ikm))
            "and 32 zeros is the same function — both pad to the same block")
        (is (not= nh-zeros (kdf/extract k (vec (repeat 200 0)) ikm))
            "past the block size it stops being the same: a long key is hashed")))))
