(ns hpke.rfc9180-test
  "Every mode of RFC 9180 Appendix A.2, against the RFC.

  A.2 is this library's suite exactly — DHKEM(X25519, HKDF-SHA256),
  HKDF-SHA256, ChaCha20Poly1305 — and it publishes base, PSK, Auth and
  AuthPSK. So none of what follows is another implementation's answer; the
  differential oracle in `oracle/` is a second opinion, not the first one.

  The vectors are generated by `scripts/extract_rfc9180.cljs` from a text
  pinned by sha256, because transcription is the step that has failed here
  before: an earlier suite claimed A.2 vectors and had A.1's `ikmR`.

  ## What each mode is asked

  `DeriveKeyPair` on every ikm the section publishes, then the KEM's own
  output (`enc` and `shared_secret`), then the key schedule (`key`,
  `base_nonce`, `exporter_secret`, and `key_schedule_context` — the value the
  four modes actually differ in), then six sealings at the published sequence
  numbers, then three exports, then the whole thing again from the recipient
  side.

  The sequence numbers are 0, 1, 2, 4, 255 and 256. The last two are the
  reason to assert them: 255 and 256 are where a byte-at-a-time nonce counter
  carries, and `compute-nonce` builds its bytes by division precisely so that
  it can."
  (:require [clojure.test :refer [deftest is testing]]
            [hpke.core :as hpke]
            [hpke.dhkem :as dhkem]
            [hpke.rfc9180-a2 :as rfc]))

(defn- h [s] (hpke/unhex s))
(defn- x [bs] (hpke/hex bs))
(defn- n [s] #?(:clj (Long/parseLong s) :cljs (js/parseInt s 10)))

(defn- kp
  "The key pair a section publishes, derived rather than read.

  Both are asserted: deriving it exercises `DeriveKeyPair`, and comparing it
  to the published `sk`/`pk` is what makes the derivation checkable. A wrong
  `DeriveKeyPair` is the one failure in this file that would otherwise be
  silent — every later value would be self-consistently wrong."
  [v ikm-k sk-k pk-k]
  (let [d (dhkem/derive-key-pair (h (get v ikm-k)))]
    (is (= (get v sk-k) (x (:private d))) (str ikm-k " -> " sk-k))
    (is (= (get v pk-k) (x (:public d))) (str ikm-k " -> " pk-k))
    d))

(defn- check-context
  "The four key-schedule outputs the RFC publishes."
  [v ctx label]
  (testing label
    (is (= (:key-schedule-context v) (x (:key-schedule-context ctx))) "key_schedule_context")
    (is (= (:key v) (x (:key ctx))) "key")
    (is (= (:base-nonce v) (x (:base-nonce ctx))) "base_nonce")
    (is (= (:exporter-secret v) (x (:exporter-secret ctx))) "exporter_secret")))

(defn- check-encryptions
  [v ctx]
  (doseq [e (:encryptions v)]
    (testing (str "seq " (:sequence-number e))
      (let [at (assoc ctx :seq (n (:sequence-number e)))
            sealed (hpke/seal at (h (:aad e)) (h (:pt e)))]
        (is (= :ok (:status sealed)))
        (is (= (:ct e) (x (:bytes sealed))) "ct")
        (let [opened (hpke/open at (h (:aad e)) (h (:ct e)))]
          (is (= :ok (:status opened)))
          (is (= (:pt e) (x (:bytes opened))) "pt")
          (is (= (inc (n (:sequence-number e))) (:seq (:context opened)))
              "open advances the sequence number"))))))

(defn- check-exports
  [v ctx]
  (doseq [e (:exports v)]
    (testing (str "export ctx=" (pr-str (:exporter-context e)))
      (is (= (:exported-value e)
             (x (hpke/export ctx (h (:exporter-context e)) (n (:l e)))))))))

(defn- check-kem
  "`enc` and `shared_secret` — the KEM's own two outputs, before the key
  schedule touches them."
  [v kem]
  (is (= :ok (:status kem)))
  (is (= (:enc v) (x (:enc kem))) "enc")
  (is (= (:shared-secret v) (x (:shared-secret kem))) "shared_secret"))

;; ── the four modes ───────────────────────────────────────────────────────────

(deftest a2-1-base
  (let [v (:base rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        info (h (:info v))]
    (is (= 0 (n (:mode v))) "this section is mode_base")
    (check-kem v (dhkem/encap (:public r) eph))
    (let [s (hpke/setup-base-sender (:public r) info eph)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-base-recipient (h (:enc v)) r info)]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-2-psk
  (let [v (:psk rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))]
    (is (= 1 (n (:mode v))) "this section is mode_psk")
    (check-kem v (dhkem/encap (:public r) eph))
    (let [s (hpke/setup-psk-sender (:public r) info psk psk-id eph)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info psk psk-id)]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-3-auth
  (let [v (:auth rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        snd (kp v :ikms :sksm :pksm)
        info (h (:info v))]
    (is (= 2 (n (:mode v))) "this section is mode_auth")
    (check-kem v (dhkem/auth-encap (:public r) eph snd))
    (let [s (hpke/setup-auth-sender (:public r) info eph snd)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-auth-recipient (h (:enc v)) r info (:public snd))]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-4-auth-psk
  (let [v (:auth-psk rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        snd (kp v :ikms :sksm :pksm)
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))]
    (is (= 3 (n (:mode v))) "this section is mode_auth_psk")
    (check-kem v (dhkem/auth-encap (:public r) eph snd))
    (let [s (hpke/setup-auth-psk-sender (:public r) info psk psk-id eph snd)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-auth-psk-recipient (h (:enc v)) r info psk psk-id (:public snd))]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

;; ── the modes are actually distinct ──────────────────────────────────────────

(deftest modes-do-not-collide
  (testing "four sections, four key_schedule_contexts, four keys"
    (let [ctxs (mapv #(get-in rfc/vectors [% :key-schedule-context])
                     [:base :psk :auth :auth-psk])
          keys- (mapv #(get-in rfc/vectors [% :key]) [:base :psk :auth :auth-psk])]
      (is (= 4 (count (set ctxs))))
      (is (= 4 (count (set keys-))))
      (is (= ["00" "01" "02" "03"] (mapv #(subs % 0 2) ctxs))
          "the mode byte leads the context")))

  (testing "base and PSK-with-empty-PSK would differ even if the PSK were dropped"
    ;; Not a vector, an argument: the RFC hashes an empty psk_id and salts
    ;; with an empty psk in base mode too, so the ONLY thing separating the
    ;; two schedules is the leading mode byte. If it were dropped, a base
    ;; context and a (rejected) empty-PSK context would be the same bytes.
    (let [ss (vec (range 32))
          base (hpke/key-schedule hpke/mode-base ss [] [] [])
          psk-shaped (hpke/key-schedule hpke/mode-psk ss [] [1] [2])]
      (is (not= (:key base) (:key psk-shaped)))
      (is (= [hpke/mode-base] (take 1 (:key-schedule-context base))))
      (is (= [hpke/mode-psk] (take 1 (:key-schedule-context psk-shaped)))))))

;; ── the PSK input rules ──────────────────────────────────────────────────────

(deftest psk-input-validation
  (let [v (:psk rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        eph (dhkem/derive-key-pair (h (:ikme v)))
        psk (h (:psk v))
        psk-id (h (:psk-id v))
        info (h (:info v))]

    (testing "half a PSK is refused, in both directions"
      (is (= :inconsistent-psk-inputs
             (:reason (hpke/setup-psk-sender (:public r) info psk [] eph))))
      (is (= :inconsistent-psk-inputs
             (:reason (hpke/setup-psk-sender (:public r) info [] psk-id eph)))))

    (testing "a PSK handed to a mode that ignores it is refused, not dropped"
      (is (= :psk-not-needed-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-base psk psk-id))))
      (is (= :psk-not-needed-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-auth psk psk-id)))))

    (testing "a mode that needs one and did not get it is refused"
      (is (= :psk-required-in-mode
             (:reason (hpke/setup-psk-sender (:public r) info [] [] eph))))
      (is (= :psk-required-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-auth-psk [] [])))))

    (testing "the valid combinations pass"
      (is (nil? (hpke/psk-inputs-error hpke/mode-base [] [])))
      (is (nil? (hpke/psk-inputs-error hpke/mode-auth [] [])))
      (is (nil? (hpke/psk-inputs-error hpke/mode-psk psk psk-id)))
      (is (nil? (hpke/psk-inputs-error hpke/mode-auth-psk psk psk-id))))))

;; ── authentication is enforced by decryption ─────────────────────────────────

(deftest auth-rejects-the-wrong-sender
  (let [v (:auth rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        snd (dhkem/derive-key-pair (h (:ikms v)))
        impostor (dhkem/derive-key-pair (vec (repeat 32 7)))
        info (h (:info v))
        e (first (:encryptions v))
        rc (hpke/setup-auth-recipient (h (:enc v)) r info (:public impostor))]

    (testing "a wrong sender key still produces a context — the KEM has
              nothing to compare against"
      (is (= :ok (:status rc)))
      (is (not= (:key v) (x (:key (:context rc))))))

    (testing "and the first open is what rejects"
      (is (= :authentication-failed
             (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e)))))))

    (testing "while the real sender key opens it"
      (let [good (hpke/setup-auth-recipient (h (:enc v)) r info (:public snd))]
        (is (= (:pt e) (x (:bytes (hpke/open (:context good) (h (:aad e)) (h (:ct e))))))))))

  (testing "a malformed sender key is refused by length before any DH"
    (let [v (:auth rfc/vectors)
          r (dhkem/derive-key-pair (h (:ikmr v)))]
      (is (= :bad-sender-key-length
             (:reason (hpke/setup-auth-recipient (h (:enc v)) r [] (vec (repeat 31 0))))))
      (is (= :non-contributory-dh
             (:reason (hpke/setup-auth-recipient (h (:enc v)) r [] (vec (repeat 32 0)))))))))

;; ── PSK mode rejects the wrong PSK ───────────────────────────────────────────

(deftest psk-rejects-the-wrong-key
  (let [v (:psk rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))
        e (first (:encryptions v))]

    (testing "a wrong psk"
      (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info (vec (repeat 32 9)) psk-id)]
        (is (= :authentication-failed
               (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e))))))))

    (testing "a wrong psk_id — it is hashed into the context, so it binds too"
      (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info psk [0])]
        (is (= :authentication-failed
               (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e))))))))))

;; ── single-shot ──────────────────────────────────────────────────────────────

(deftest single-shot-round-trips-every-mode
  (let [pt (h "48656c6c6f") aad (h "0102")]
    (testing "base"
      (let [v (:base rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            s (hpke/seal-base (:public r) [] aad pt eph)]
        (is (= pt (:bytes (hpke/open-base (:enc s) r [] aad (:bytes s)))))))

    (testing "psk"
      (let [v (:psk rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            psk (h (:psk v)) psk-id (h (:psk-id v))
            s (hpke/seal-psk (:public r) [] aad pt psk psk-id eph)]
        (is (= pt (:bytes (hpke/open-psk (:enc s) r [] aad (:bytes s) psk psk-id))))))

    (testing "auth"
      (let [v (:auth rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            snd (dhkem/derive-key-pair (h (:ikms v)))
            s (hpke/seal-auth (:public r) [] aad pt eph snd)]
        (is (= pt (:bytes (hpke/open-auth (:enc s) r [] aad (:bytes s) (:public snd)))))))

    (testing "auth-psk"
      (let [v (:auth-psk rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            snd (dhkem/derive-key-pair (h (:ikms v)))
            psk (h (:psk v)) psk-id (h (:psk-id v))
            s (hpke/seal-auth-psk (:public r) [] aad pt psk psk-id eph snd)]
        (is (= pt (:bytes (hpke/open-auth-psk (:enc s) r [] aad (:bytes s)
                                              psk psk-id (:public snd)))))))))
