(ns hpke.rfc9180-test
  "Every mode of RFC 9180 Appendix A.2, against the RFC.

  A.2 is this library's suite exactly — DHKEM(X25519, HKDF-SHA256),
  HKDF-SHA256, ChaCha20Poly1305 — and it publishes base, PSK, Auth and
  AuthPSK. So none of what follows is another implementation's answer; the
  differential oracle in `oracle/` is a second opinion, not the first one.

  The vectors are generated by `scripts/extract_rfc9180.cljs` from a text
  pinned by sha256, because transcription is the step that has failed here
  before: an earlier suite claimed A.2 vectors and had A.1's `ikmR`.

  ## What each mode is asked

  `DeriveKeyPair` on every ikm the section publishes, then the KEM's own
  output (`enc` and `shared_secret`), then the key schedule (`key`,
  `base_nonce`, `exporter_secret`, and `key_schedule_context` — the value the
  four modes actually differ in), then six sealings at the published sequence
  numbers, then three exports, then the whole thing again from the recipient
  side.

  The sequence numbers are 0, 1, 2, 4, 255 and 256. The last two are the
  reason to assert them: 255 and 256 are where a byte-at-a-time nonce counter
  carries, and `compute-nonce` builds its bytes by division precisely so that
  it can."
  (:require [clojure.test :refer [deftest is testing]]
            [hpke.core :as hpke]
            [hpke.dhkem :as dhkem]
            [hpke.rfc9180-a2 :as rfc]))

(defn- h [s] (hpke/unhex s))
(defn- x [bs] (hpke/hex bs))
(defn- n [s] #?(:clj (Long/parseLong s) :cljs (js/parseInt s 10)))

(defn- kp
  "The key pair a section publishes, derived rather than read.

  Both are asserted: deriving it exercises `DeriveKeyPair`, and comparing it
  to the published `sk`/`pk` is what makes the derivation checkable. A wrong
  `DeriveKeyPair` is the one failure in this file that would otherwise be
  silent — every later value would be self-consistently wrong."
  [v ikm-k sk-k pk-k]
  (let [d (dhkem/derive-key-pair (h (get v ikm-k)))]
    (is (= (get v sk-k) (x (:private d))) (str ikm-k " -> " sk-k))
    (is (= (get v pk-k) (x (:public d))) (str ikm-k " -> " pk-k))
    d))

(defn- check-context
  "The four key-schedule outputs the RFC publishes."
  [v ctx label]
  (testing label
    (is (= (:key-schedule-context v) (x (:key-schedule-context ctx))) "key_schedule_context")
    (is (= (:key v) (x (:key ctx))) "key")
    (is (= (:base-nonce v) (x (:base-nonce ctx))) "base_nonce")
    (is (= (:exporter-secret v) (x (:exporter-secret ctx))) "exporter_secret")))

(defn- check-encryptions
  [v ctx]
  (doseq [e (:encryptions v)]
    (testing (str "seq " (:sequence-number e))
      (let [at (assoc ctx :seq (n (:sequence-number e)))
            sealed (hpke/seal at (h (:aad e)) (h (:pt e)))]
        (is (= :ok (:status sealed)))
        (is (= (:ct e) (x (:bytes sealed))) "ct")
        (let [opened (hpke/open at (h (:aad e)) (h (:ct e)))]
          (is (= :ok (:status opened)))
          (is (= (:pt e) (x (:bytes opened))) "pt")
          (is (= (inc (n (:sequence-number e))) (:seq (:context opened)))
              "open advances the sequence number"))))))

(defn- check-exports
  [v ctx]
  (doseq [e (:exports v)]
    (testing (str "export ctx=" (pr-str (:exporter-context e)))
      (is (= (:exported-value e)
             (x (hpke/export ctx (h (:exporter-context e)) (n (:l e)))))))))

(defn- check-kem
  "`enc` and `shared_secret` — the KEM's own two outputs, before the key
  schedule touches them."
  [v kem]
  (is (= :ok (:status kem)))
  (is (= (:enc v) (x (:enc kem))) "enc")
  (is (= (:shared-secret v) (x (:shared-secret kem))) "shared_secret"))

;; ── the four modes ───────────────────────────────────────────────────────────

(defn- vecs [app k] (get-in rfc/by-appendix [app k]))
(def ^:private suite-of {:a1 hpke/aes-128-gcm :a2 hpke/chacha20-poly1305})

(deftest a2-1-base
  (let [v (:base rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        info (h (:info v))]
    (is (= 0 (n (:mode v))) "this section is mode_base")
    (check-kem v (dhkem/encap (:public r) eph))
    (let [s (hpke/setup-base-sender (:public r) info eph)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-base-recipient (h (:enc v)) r info)]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-2-psk
  (let [v (:psk rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))]
    (is (= 1 (n (:mode v))) "this section is mode_psk")
    (check-kem v (dhkem/encap (:public r) eph))
    (let [s (hpke/setup-psk-sender (:public r) info psk psk-id eph)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info psk psk-id)]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-3-auth
  (let [v (:auth rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        snd (kp v :ikms :sksm :pksm)
        info (h (:info v))]
    (is (= 2 (n (:mode v))) "this section is mode_auth")
    (check-kem v (dhkem/auth-encap (:public r) eph snd))
    (let [s (hpke/setup-auth-sender (:public r) info eph snd)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-auth-recipient (h (:enc v)) r info (:public snd))]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

(deftest a2-4-auth-psk
  (let [v (:auth-psk rfc/vectors)
        eph (kp v :ikme :skem :pkem)
        r (kp v :ikmr :skrm :pkrm)
        snd (kp v :ikms :sksm :pksm)
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))]
    (is (= 3 (n (:mode v))) "this section is mode_auth_psk")
    (check-kem v (dhkem/auth-encap (:public r) eph snd))
    (let [s (hpke/setup-auth-psk-sender (:public r) info psk psk-id eph snd)]
      (is (= :ok (:status s)))
      (is (= (:enc v) (x (:enc s))))
      (check-context v (:context s) "sender")
      (check-encryptions v (:context s))
      (check-exports v (:context s)))
    (let [rc (hpke/setup-auth-psk-recipient (h (:enc v)) r info psk psk-id (:public snd))]
      (is (= :ok (:status rc)))
      (check-context v (:context rc) "recipient")
      (check-encryptions v (:context rc)))))

;; ── the modes are actually distinct ──────────────────────────────────────────

(deftest modes-do-not-collide
  (testing "four sections, four key_schedule_contexts, four keys"
    (let [ctxs (mapv #(get-in rfc/vectors [% :key-schedule-context])
                     [:base :psk :auth :auth-psk])
          keys- (mapv #(get-in rfc/vectors [% :key]) [:base :psk :auth :auth-psk])]
      (is (= 4 (count (set ctxs))))
      (is (= 4 (count (set keys-))))
      (is (= ["00" "01" "02" "03"] (mapv #(subs % 0 2) ctxs))
          "the mode byte leads the context")))

  (testing "base and PSK-with-empty-PSK would differ even if the PSK were dropped"
    ;; Not a vector, an argument: the RFC hashes an empty psk_id and salts
    ;; with an empty psk in base mode too, so the ONLY thing separating the
    ;; two schedules is the leading mode byte. If it were dropped, a base
    ;; context and a (rejected) empty-PSK context would be the same bytes.
    (let [ss (vec (range 32))
          base (hpke/key-schedule hpke/mode-base ss [] [] [])
          psk-shaped (hpke/key-schedule hpke/mode-psk ss [] [1] [2])]
      (is (not= (:key base) (:key psk-shaped)))
      (is (= [hpke/mode-base] (take 1 (:key-schedule-context base))))
      (is (= [hpke/mode-psk] (take 1 (:key-schedule-context psk-shaped)))))))

;; ── the PSK input rules ──────────────────────────────────────────────────────

(deftest psk-input-validation
  (let [v (:psk rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        eph (dhkem/derive-key-pair (h (:ikme v)))
        psk (h (:psk v))
        psk-id (h (:psk-id v))
        info (h (:info v))]

    (testing "half a PSK is refused, in both directions"
      (is (= :inconsistent-psk-inputs
             (:reason (hpke/setup-psk-sender (:public r) info psk [] eph))))
      (is (= :inconsistent-psk-inputs
             (:reason (hpke/setup-psk-sender (:public r) info [] psk-id eph)))))

    (testing "a PSK handed to a mode that ignores it is refused, not dropped"
      (is (= :psk-not-needed-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-base psk psk-id))))
      (is (= :psk-not-needed-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-auth psk psk-id)))))

    (testing "a mode that needs one and did not get it is refused"
      (is (= :psk-required-in-mode
             (:reason (hpke/setup-psk-sender (:public r) info [] [] eph))))
      (is (= :psk-required-in-mode
             (:reason (hpke/psk-inputs-error hpke/mode-auth-psk [] [])))))

    (testing "the valid combinations pass"
      (is (nil? (hpke/psk-inputs-error hpke/mode-base [] [])))
      (is (nil? (hpke/psk-inputs-error hpke/mode-auth [] [])))
      (is (nil? (hpke/psk-inputs-error hpke/mode-psk psk psk-id)))
      (is (nil? (hpke/psk-inputs-error hpke/mode-auth-psk psk psk-id))))))

;; ── authentication is enforced by decryption ─────────────────────────────────

(deftest auth-rejects-the-wrong-sender
  (let [v (:auth rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        snd (dhkem/derive-key-pair (h (:ikms v)))
        impostor (dhkem/derive-key-pair (vec (repeat 32 7)))
        info (h (:info v))
        e (first (:encryptions v))
        rc (hpke/setup-auth-recipient (h (:enc v)) r info (:public impostor))]

    (testing "a wrong sender key still produces a context — the KEM has
              nothing to compare against"
      (is (= :ok (:status rc)))
      (is (not= (:key v) (x (:key (:context rc))))))

    (testing "and the first open is what rejects"
      (is (= :authentication-failed
             (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e)))))))

    (testing "while the real sender key opens it"
      (let [good (hpke/setup-auth-recipient (h (:enc v)) r info (:public snd))]
        (is (= (:pt e) (x (:bytes (hpke/open (:context good) (h (:aad e)) (h (:ct e))))))))))

  (testing "a malformed sender key is refused by length before any DH"
    (let [v (:auth rfc/vectors)
          r (dhkem/derive-key-pair (h (:ikmr v)))]
      (is (= :bad-sender-key-length
             (:reason (hpke/setup-auth-recipient (h (:enc v)) r [] (vec (repeat 31 0))))))
      (is (= :non-contributory-dh
             (:reason (hpke/setup-auth-recipient (h (:enc v)) r [] (vec (repeat 32 0)))))))))

;; ── PSK mode rejects the wrong PSK ───────────────────────────────────────────

(deftest psk-rejects-the-wrong-key
  (let [v (:psk rfc/vectors)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        info (h (:info v))
        psk (h (:psk v))
        psk-id (h (:psk-id v))
        e (first (:encryptions v))]

    (testing "a wrong psk"
      (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info (vec (repeat 32 9)) psk-id)]
        (is (= :authentication-failed
               (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e))))))))

    (testing "a wrong psk_id — it is hashed into the context, so it binds too"
      (let [rc (hpke/setup-psk-recipient (h (:enc v)) r info psk [0])]
        (is (= :authentication-failed
               (:reason (hpke/open (:context rc) (h (:aad e)) (h (:ct e))))))))))

;; ── single-shot ──────────────────────────────────────────────────────────────

(deftest single-shot-round-trips-every-mode
  (let [pt (h "48656c6c6f") aad (h "0102")]
    (testing "base"
      (let [v (:base rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            s (hpke/seal-base (:public r) [] aad pt eph)]
        (is (= pt (:bytes (hpke/open-base (:enc s) r [] aad (:bytes s)))))))

    (testing "psk"
      (let [v (:psk rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            psk (h (:psk v)) psk-id (h (:psk-id v))
            s (hpke/seal-psk (:public r) [] aad pt psk psk-id eph)]
        (is (= pt (:bytes (hpke/open-psk (:enc s) r [] aad (:bytes s) psk psk-id))))))

    (testing "auth"
      (let [v (:auth rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            snd (dhkem/derive-key-pair (h (:ikms v)))
            s (hpke/seal-auth (:public r) [] aad pt eph snd)]
        (is (= pt (:bytes (hpke/open-auth (:enc s) r [] aad (:bytes s) (:public snd)))))))

    (testing "auth-psk"
      (let [v (:auth-psk rfc/vectors)
            r (dhkem/derive-key-pair (h (:ikmr v)))
            eph (dhkem/derive-key-pair (h (:ikme v)))
            snd (dhkem/derive-key-pair (h (:ikms v)))
            psk (h (:psk v)) psk-id (h (:psk-id v))
            s (hpke/seal-auth-psk (:public r) [] aad pt psk psk-id eph snd)]
        (is (= pt (:bytes (hpke/open-auth-psk (:enc s) r [] aad (:bytes s)
                                              psk psk-id (:public snd)))))))))

;; ── the AEAD is a parameter, and A.1 proves it ───────────────────────────────
;;
;; A.1 and A.2 are the same KEM and the same KDF. They differ in one
;; identifier, and that identifier is inside `suite_id`, which is inside
;; every LabeledExtract and LabeledExpand in the key schedule. So running
;; both is the cheapest possible check that the suite is a value here rather
;; than a constant somewhere: nothing about these two sections can be made to
;; agree by accident.

(deftest both-appendices-all-four-modes
  (doseq [app [:a1 :a2]
          [k mode-n] {:base 0 :psk 1 :auth 2 :auth-psk 3}]
    (let [s (suite-of app)
          v (vecs app k)
          info (h (:info v))
          psk (when (:psk v) (h (:psk v)))
          psk-id (when (:psk-id v) (h (:psk-id v)))
          eph (dhkem/derive-key-pair (h (:ikme v)))
          r (dhkem/derive-key-pair (h (:ikmr v)))
          snd (when (:ikms v) (dhkem/derive-key-pair (h (:ikms v))))]
      (testing (str (name app) " " (name k))
        (is (= mode-n (n (:mode v))) "the section is the mode it says")
        (is (= (n (:aead-id v)) (:aead-id s)) "and the AEAD this suite names")

        (let [setup (case k
                      :base (hpke/setup-base-sender s (:public r) info eph)
                      :psk (hpke/setup-psk-sender s (:public r) info psk psk-id eph)
                      :auth (hpke/setup-auth-sender s (:public r) info eph snd)
                      :auth-psk (hpke/setup-auth-psk-sender s (:public r) info psk psk-id eph snd))]
          (is (= :ok (:status setup)))
          (is (= (:enc v) (x (:enc setup))) "enc")
          (check-context v (:context setup) "sender")
          (check-encryptions v (:context setup))
          (check-exports v (:context setup)))

        (let [rc (case k
                   :base (hpke/setup-base-recipient s (h (:enc v)) r info)
                   :psk (hpke/setup-psk-recipient s (h (:enc v)) r info psk psk-id)
                   :auth (hpke/setup-auth-recipient s (h (:enc v)) r info (:public snd))
                   :auth-psk (hpke/setup-auth-psk-recipient s (h (:enc v)) r info psk psk-id (:public snd)))]
          (is (= :ok (:status rc)))
          (check-context v (:context rc) "recipient")
          (check-encryptions v (:context rc)))))))

(deftest the-aeads-are-actually-different
  (testing "A.1 keys are 16 bytes and A.2's are 32 — Nk follows the suite"
    (is (= 32 (count (h (:key (vecs :a2 :base)))))) 
    (is (= 16 (count (h (:key (vecs :a1 :base)))))))

  (testing "the same inputs under two AEADs derive unrelated key schedules"
    ;; Same shared secret, same info, same mode. Only aead_id differs, and it
    ;; differs inside suite_id, so every derived byte does.
    (let [ss (vec (range 32))
          a (hpke/key-schedule hpke/aes-128-gcm hpke/mode-base ss [] [] [])
          c (hpke/key-schedule hpke/chacha20-poly1305 hpke/mode-base ss [] [] [])]
      (is (= 16 (count (:key a))))
      (is (= 32 (count (:key c))))
      (is (not= (:base-nonce a) (:base-nonce c)))
      (is (not= (:exporter-secret a) (:exporter-secret c)))
      (is (not= (:key-schedule-context a) (:key-schedule-context c))
          "and so does the context: suite_id is an input to LabeledExtract, so
           the AEAD identifier reaches psk_id_hash and info_hash too")))

  (testing "which the RFC's own two sections confirm"
    ;; Same mode byte, same KEM, same KDF, same info, same empty psk_id --
    ;; and the published contexts differ, in every mode. If they did not,
    ;; the assertion above would be a statement about this implementation
    ;; rather than about HPKE.
    (doseq [k [:base :psk :auth :auth-psk]]
      (is (not= (:key-schedule-context (vecs :a1 k))
                (:key-schedule-context (vecs :a2 k)))
          (str (name k) ": A.1 and A.2 publish different contexts"))
      (is (= (subs (:key-schedule-context (vecs :a1 k)) 0 2)
             (subs (:key-schedule-context (vecs :a2 k)) 0 2))
          (str (name k) ": but the same leading mode byte"))))

  (testing "the registry lists only what can run"
    (is (= #{0x0001 0x0002 0x0003} (set (keys hpke/suites))))
    (is (every? fn? (map :seal (vals hpke/suites))))
    (is (every? fn? (map :open (vals hpke/suites))))))

(deftest aes-256-gcm-round-trips-though-the-rfc-does-not-publish-it
  ;; RFC 9180 has no X25519 + AES-256-GCM section, so this is a round-trip
  ;; and a suite-separation check, not a known-answer test. It is labelled
  ;; that way on purpose: the two above ARE known-answer tests and this one
  ;; is not, and a reader should not have to infer which is which.
  (let [v (vecs :a2 :base)
        r (dhkem/derive-key-pair (h (:ikmr v)))
        eph (dhkem/derive-key-pair (h (:ikme v)))
        pt (h "48656c6c6f20776f726c64") aad (h "0102")
        s (hpke/setup-auth-sender hpke/aes-256-gcm (:public r) [] eph r)]
    (is (= :ok (:status s)))
    (is (= 32 (count (:key (:context s)))))
    (let [sealed (hpke/seal (:context s) aad pt)
          rc (hpke/setup-auth-recipient hpke/aes-256-gcm (:enc s) r [] (:public r))]
      (is (= pt (:bytes (hpke/open (:context rc) aad (:bytes sealed)))))
      (testing "and a different AEAD does not open it"
        (let [wrong (hpke/setup-auth-recipient hpke/aes-128-gcm (:enc s) r [] (:public r))]
          (is (= :authentication-failed
                 (:reason (hpke/open (:context wrong) aad (:bytes sealed))))))))))
